# Generated by Django 4.0.3 on 2022-03-31 17:05

from django.db import migrations, models
import django.db.models.deletion
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='name',
        ),
        migrations.AddField(
            model_name='feeding',
            name='date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeding',
            name='recipe2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeding',
            name='event',
            field=models.CharField(choices=[('B', 'BirthDay'), ('r', 'religiousceremonie'), ('D', 'DinnerParty')], default='B', max_length=1),
        ),
    ]
